server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ycg
    url: jdbc:mysql://127.0.0.1:3306/daily?characterEncoding=utf-8&useSSL=false
  redis:
    host: localhost
    port: 6379
    password: ycg
  web:
    resources:
      static-locations: file:D:\daily\
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: idDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置type-enums-package只对注解方式的枚举处理能提前加载缓存. 使用注解方式 VO也要使用枚举类
  type-enums-package: com.ycg.daily.enums

